php:
  preset: laravel
  disabled:
    - no_unused_imports
  finder:iuiu
    not-name:
      - index.php
      - server.php
      - diuwqudiqwiuduiqewda
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
